### ISSUE TITLE
留意到这个项目,发现跟我在做的相似,不过技术栈不同

### ISSUE THREAD

**Issue by alphasnow** [NextEcho/Phospherus#1]
后台前端页面 antd pro
博客前端页面 nextjs
后端接口 
使用wire管理依赖 
使用gorm+gen生成数据库操作方法

**Comment by NextEcho** [comment]
@alphasnow 是的，技术栈主要都是上面你说的那些，这个项目也是我打算迭代的博客，许多功能都还没完善，现在也只是在逐渐摸索，有更多的想法，可以一起交流

**Comment by alphasnow** [comment]
如果用单例不用依赖可以考虑把gobal放到pkg/g 做的像gf框架一样 使用g.Config或g.Viper用起来更便捷一些。
对于web服务的架构，还是比较麻烦。

**Comment by NextEcho** [comment]
@alphasnow 非常感谢你的建议，使用 wire 来实现依赖注入我目前暂时没有过多了解，我后续会详细看看的

1. 我起初创建 pkg 的思路是将其作为工具包来使用的（类似于Java中经常使用的 utils），而 global 这个名称我认为会让我以及其他人更加直观地了解该包的用处（参考的是 [gin-vue-admin](https://github.com/flipped-aurora/gin-vue-admin) 这个项目的文件布局）

2. 嘿嘿，可以看出来我其实参考了 GoFrame 框架的文件结构，我的整个 Go 项目的文件布局其实就是 gin-vue-admin 和 GoFrame 文件布局的杂交，然后再参杂了一些我自己的理解。确实 web 服务的架构布局是比较难搞的，对于我这种有代码洁癖的人来说，有时候也不得不做出一些妥协

**Comment by alphasnow** [comment]
以Golang标准布局会更好一点,仓库在[https://github.com/golang-standards/project-layout](https://github.com/golang-standards/project-layout)
另外copier可用功能很多, 通过写通用的 TypeConverter 与 FieldNameMapping 可以极少的代码实现 model 数据到 response数据的转换
就像下面的测试一样, 完整的分层代码在附件 [util-copier.zip](https://github.com/user-attachments/files/16225538/util-copier.zip)

```go
package service

import (
	"encoding/json"
	"testing"
	"time"
	"util-copier/model"
	"util-copier/transform"
)

func Test_ArticleService_ShowResp(t *testing.T) {
	m := model.Article{
		Title:          "article title",
		Favourites:     123,
		Views:          345,
		MetaKeywords:   "website,golang",
		CreatedAt:      time.Date(2024, 1, 1, 0, 0, 0, 0, time.Local),
		UpdatedAt:      time.Date(2024, 2, 2, 0, 0, 0, 0, time.Local),
		ArticleContent: model.ArticleContent{"article content"},
		ArticleCover:   model.WebAttribute{"/upload/article/123456.jpg"},
	}

	factory := &transform.WebAttributeFactory{"http://127.0.0.1:8080"}
	svc := &ArticleService{factory}
	resp, err := svc.ShowResp(&m)
	if err != nil {
		t.Fatalf("ArticleService ShowResp got error %s", err.Error())
	}

	gotJson, _ := json.Marshal(resp)
	wantedJson := "{\"Title\":\"article title\",\"Likes\":123,\"Clicks\":345,\"Keywords\":\"website,golang,http\",\"Content\":\"article content\",\"CreatedAt\":1704038400,\"UpdateTime\":\"2024-02-02 00:00:00\",\"Cover\":\"http://127.0.0.1:8080/upload/article/123456.jpg\"}"
	if string(gotJson) != wantedJson {
		t.Fatalf("ArticleService ShowResp wanted %s got %s", wantedJson, gotJson)
	}
}
```
